### ISSUE TITLE
Missing 404 Error page not found

### ISSUE THREAD

**Issue by PratikMane0112** [Muskansahuincredible/StudyNotion-An-Online-Education-Platform#17]
When there is any error in website while navigating through pages, there is not a 404 error page.

![Screenshot 2024-05-14 143949](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/153143167/7c6421a7-4b56-475c-9d75-2d1fd2c5612e)

I will create a good 404 error page which will match with website environment.
Below is just an rough idea that I have :

![404 error not found](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/153143167/682deb3f-d1e1-4cb0-bbee-b9542110f34f)

I will edit it to add button to navigate to home page & also make it responsive to have a unique error page for website.

**Expected behavior**
A clear understanding to users using website when such error occurs and the navigate back to home page.

Looking forward to contribute more on StudyNotion bugs....

**Comment by techmannih** [comment]
Good catch @PratikMane0112 
but It will be better in dark mode which is similar to website theme, please add a Screen Shot in dark mode

**Comment by PratikMane0112** [comment]
Ok, I will add screenshot in dark mode.

**Comment by Vaibhavs1612** [comment]
I would like to work on this issue as a contributor to the GSSOC. please assign this to me!
I have relevant skills that definitely help to enhance the website.

**Comment by techmannih** [comment]
assigned both @Vaibhavs1612 and @PratikMane0112, who will first raise pr and first serve

**Comment by PratikMane0112** [comment]
Actually @Vaibhavs1612  the issue is solved & also got merged. Check PR #25

**Comment by techmannih** [comment]
not, this is not solved fully, need to raise another pr for visit undefined endpoints. it has also same error page as before

**Comment by techmannih** [comment]
see here 
![Screenshot 2024-05-23 000619](https://github.com/Muskansahuincredible/StudyNotion-An-Online-Education-Platform/assets/125847751/32e2e273-284e-421d-9684-867ad0519d0c)

**Comment by PratikMane0112** [comment]
Ok, I will look into it.

**Comment by techmannih** [comment]
> not, this is not solved fully, need to raise another pr for visit undefined endpoints. it has also same error page as before

same error which is not solve, please find another solution or I will tell you how to solve this

**Comment by PratikMane0112** [comment]
Okay.

**Comment by Unknnown-Mayank** [comment]
Hello 
I have relevant skills to solve this issue
I can bring the 404 error in dark mode in an attractive view
which will look good also
Please . let me the know if the issue is still open
Thanks
